import { z } from 'zod';

export const setObjectConceptDTOSchema = z.object({
    // is_active: z.string({ message: 'required field!' }),
    // status: z.string({ message: 'required field!' }).min(1, 'required field!'),
    // reject_comment: z.string({ message: 'required field!' }).min(1, 'required field!'),
    project_name: z.string({ message: 'required field!' }).min(1, 'required field!'),
    project_type: z.string({ message: 'required field!' }).min(1, 'required field!'),
    volume_work: z.string({ message: 'required field!' }).min(1, 'required field!'),
    description_documents_list: z.string({ message: 'required field!' }).min(1, 'required field!'),
    point3_1: z.string({ message: 'required field!' }),
    point3_2: z.string({ message: 'required field!' }),
    point3_3: z.string({ message: 'required field!' }),
    point3_4: z.string({ message: 'required field!' }),
    point3_5_a: z.string({ message: 'required field!' }),
    point3_5_b: z.string({ message: 'required field!' }),
    point3_5_v: z.string({ message: 'required field!' }),
    point3_5_g: z.string({ message: 'required field!' }),
    point3_5_d: z.string({ message: 'required field!' }),
    point3_6_a: z.number({ message: 'required field!' }).min(1, 'required field!'),
    point3_6_b_0: z.string({ message: 'required field!' }),
    point3_6_b: z.number({ message: 'required field!' }),
    point3_7: z.number({ message: 'required field!' }),
    point3_8_1: z.number({ message: 'required field!' }),
    point3_8_2: z.number({ message: 'required field!' }),
    point3_8_3: z.number({ message: 'required field!' }),
    point3_8_4: z.number({ message: 'required field!' }),
    point3_8_5: z.number({ message: 'required field!' }),
    point3_8_6: z.number({ message: 'required field!' }),
    point3_8_7: z.number({ message: 'required field!' }),
    point3_8_8: z.number({ message: 'required field!' }),
    point3_8_9: z.number({ message: 'required field!' }),
    point3_8_10: z.number({ message: 'required field!' }),
    point3_8_11: z.number({ message: 'required field!' }),
    point3_8_12: z.number({ message: 'required field!' }),
    point3_8_13: z.number({ message: 'required field!' }),
    point3_8_14: z.number({ message: 'required field!' }),
    point3_8_15: z.number({ message: 'required field!' }),
    point3_8_16: z.number({ message: 'required field!' }),
    point3_8_17: z.number({ message: 'required field!' }),
    point3_8_18: z.number({ message: 'required field!' }),
    point3_8_19: z.number({ message: 'required field!' }),
    point3_8_20: z.number({ message: 'required field!' }),
    point3_8_21: z.number({ message: 'required field!' }),
    point3_8_22: z.number({ message: 'required field!' }),
    point3_8_23: z.number({ message: 'required field!' }),
    point3_9_a: z.string({ message: 'required field!' }),
    point3_9_b: z.string({ message: 'required field!' }),
    point3_9_v: z.string({ message: 'required field!' }),
    point3_9_d: z.string({ message: 'required field!' }),
    point3_9_e: z.string({ message: 'required field!' }),
    point3_9_g: z.string({ message: 'required field!' }),
    point3_10_comment: z.string({ message: 'required field!' }),
    point3_11_comment: z.string({ message: 'required field!' }),
    point3_12_comment: z.string({ message: 'required field!' }),
    point3_13: z.string({ message: 'required field!' }),
    point3_14: z.string({ message: 'required field!' }),
    point3_15: z.string({ message: 'required field!' }),
    point3_16: z.string({ message: 'required field!' }),
    point3_17: z.string({ message: 'required field!' }),
    point3_18_a: z.string({ message: 'required field!' }),
    point3_18_b: z.string({ message: 'required field!' }),
    point3_19_1: z.string({ message: 'required field!' }),
    point3_19_2: z.string({ message: 'required field!' }),
    point3_19_3: z.string({ message: 'required field!' }),
    point3_19_4: z.string({ message: 'required field!' }),
    point3_19_5: z.string({ message: 'required field!' }),
    // created_by: z.string({ message: 'required field!' }),
    // updated_by: z.string({ message: 'required field!' }),
    // file: z.string({ message: 'required field!' }),
    // application: z.string({ message: 'required field!' }),
    // region: z.string({ message: 'required field!' }),
    // district: z.string({ message: 'required field!' }),
})
