import { ROLE_LIST } from "@app/shared";
import { IMenuItem } from "@app/interfaces";
import {
  Applications,
  Monitoring,
  Conceptions,
  ObjectsSide,
  Deals,
  Investment,
  Reports,
  Finans,
  Deed,
  Projects,
  ApplicationsForm,
} from "@app/assets";

export const menu: IMenuItem[] = [
  // Arizalar
  {
    id: "/applications",
    label: "Applications",
    icon: Applications,
    href: "/applications",
    allowedRoles: [
      ROLE_LIST.APPLICANT,
      ROLE_LIST.BALANCE,
      ROLE_LIST.MINISTRY_DXSH_B_B,
      ROLE_LIST.MINISTRY_DXSH_B_X,
      ROLE_LIST.OPERATOR,
    ],
    order: {
      [ROLE_LIST.APPLICANT]: 1,
      [ROLE_LIST.BALANCE]: 1,
      [ROLE_LIST.MINISTRY_DXSH_B_B]: 1,
      [ROLE_LIST.MINISTRY_DXSH_B_X]: 1,
      [ROLE_LIST.OPERATOR]: 1,
    },
  },
  // Loyihalar
  {
    id: "/projects",
    label: "Projects",
    icon: Projects,
    href: "/projects",
    allowedRoles: [
      ROLE_LIST.BALANCE,
      ROLE_LIST.MINISTRY_DXSH_B_X,
      ROLE_LIST.REGION_OPERATOR,
      ROLE_LIST.MINISTRY_DXSH_B_B,
      ROLE_LIST.MINISTRY_M_B_B,
      ROLE_LIST.OPERATOR,
      ROLE_LIST.DEPUTY_MINISTRY,
      ROLE_LIST.MINISTRY,
      ROLE_LIST.MINISTRY_FINANCE,
      ROLE_LIST.FINANCE_EMPLOYEE,
      ROLE_LIST.HEAD,
      ROLE_LIST.APPLICANT,
    ],
    order: {
      [ROLE_LIST.HEAD]: 2,
      [ROLE_LIST.OPERATOR]: 2,
      [ROLE_LIST.REGION_OPERATOR]: 2,
      [ROLE_LIST.APPLICANT]: 2,
    },
  },
  // Obyektlar
  {
    id: "/objects",
    label: "Objects",
    icon: ObjectsSide,
    href: "/objects",
    allowedRoles: [
      ROLE_LIST.APPLICANT,
      ROLE_LIST.BASIN_B_B,
      ROLE_LIST.MINISTRY_DXSH_B_B,
      ROLE_LIST.REGION_OPERATOR,
      ROLE_LIST.ADMIN,
      ROLE_LIST.USER,
      ROLE_LIST.BALANCE,
      ROLE_LIST.MINISTRY_DXSH_B_X,
      ROLE_LIST.MINISTRY_M_B_B,
      ROLE_LIST.DEPUTY_MINISTRY,
      ROLE_LIST.MINISTRY,
      ROLE_LIST.MINISTRY_FINANCE,
      ROLE_LIST.OPERATOR,
      ROLE_LIST.HEAD,
      ROLE_LIST.FINANCE_EMPLOYEE,
    ],
    order: {
      [ROLE_LIST.APPLICANT]: 3,
      [ROLE_LIST.BASIN_B_B]: 3,
      [ROLE_LIST.BALANCE]: 3,
      [ROLE_LIST.MINISTRY_DXSH_B_B]: 3,
      [ROLE_LIST.REGION_OPERATOR]: 3,
    },
  },
  // Konsepsiya
  {
    id: "/conceptions",
    label: "Concept",
    icon: Conceptions,
    href: "/conceptions",
    allowedRoles: [
      ROLE_LIST.APPLICANT,
      ROLE_LIST.BASIN_B_B,
      ROLE_LIST.BALANCE,
      ROLE_LIST.REGION_OPERATOR,
      ROLE_LIST.MINISTRY_DXSH_B_B,
      ROLE_LIST.ADMIN,
      ROLE_LIST.USER,
      ROLE_LIST.MINISTRY_DXSH_B_X,
      ROLE_LIST.MINISTRY_M_B_B,
      ROLE_LIST.DEPUTY_MINISTRY,
      ROLE_LIST.MINISTRY,
      ROLE_LIST.MINISTRY_FINANCE,
      ROLE_LIST.OPERATOR,
      ROLE_LIST.HEAD,
      ROLE_LIST.FINANCE_EMPLOYEE,
    ],
    order: {
      [ROLE_LIST.APPLICANT]: 4,
      [ROLE_LIST.BASIN_B_B]: 4,
      [ROLE_LIST.BALANCE]: 4,
      [ROLE_LIST.MINISTRY_DXSH_B_B]: 4,
      [ROLE_LIST.REGION_OPERATOR]: 4,
    },
  },
  // Elonlar
  {
    id: "/announcements",
    label: "Announcements",
    icon: Applications,
    href: "/announcements",
    allowedRoles: [
      ROLE_LIST.APPLICANT,
      ROLE_LIST.MINISTRY_DXSH_B_B,
      ROLE_LIST.MINISTRY_M_B_B,
      ROLE_LIST.DEPUTY_MINISTRY,
      ROLE_LIST.MINISTRY,
      ROLE_LIST.MINISTRY_FINANCE,
    ],
    order: {
      [ROLE_LIST.APPLICANT]: 5,
      [ROLE_LIST.MINISTRY_DXSH_B_B]: 5,
      [ROLE_LIST.MINISTRY_M_B_B]: 5,
      [ROLE_LIST.DEPUTY_MINISTRY]: 5,
      [ROLE_LIST.MINISTRY]: 5,
      [ROLE_LIST.MINISTRY_FINANCE]: 5,
      [ROLE_LIST.REGION_OPERATOR]: 5,
      [ROLE_LIST.BASIN_B_B]: 5,
    },
  },
  // Tenderlar
  {
    id: "/tenders",
    label: "Tenders",
    icon: Applications,
    href: "/tenders",
    allowedRoles: [
      ROLE_LIST.APPLICANT,
      ROLE_LIST.MINISTRY_DXSH_B_B,
      ROLE_LIST.MINISTRY_M_B_B,
      ROLE_LIST.DEPUTY_MINISTRY,
      ROLE_LIST.MINISTRY,
      ROLE_LIST.MINISTRY_FINANCE,
    ],
    order: {
      [ROLE_LIST.APPLICANT]: 6,
      [ROLE_LIST.MINISTRY_DXSH_B_B]: 6,
      [ROLE_LIST.MINISTRY_M_B_B]: 6,
      [ROLE_LIST.DEPUTY_MINISTRY]: 6,
      [ROLE_LIST.MINISTRY]: 6,
      [ROLE_LIST.MINISTRY_FINANCE]: 6,
      [ROLE_LIST.REGION_OPERATOR]: 6,
      [ROLE_LIST.BASIN_B_B]: 6,
    },
  },
  // Bitim shartnomalar
  {
    id: "/deals",
    label: "Deals",
    icon: Deals,
    href: "/deals",

    allowedRoles: [
      ROLE_LIST.APPLICANT,
      ROLE_LIST.MINISTRY_DXSH_B_B,
      ROLE_LIST.MINISTRY_M_B_B,
      ROLE_LIST.DEPUTY_MINISTRY,
      ROLE_LIST.MINISTRY,
      ROLE_LIST.MINISTRY_FINANCE,
      ROLE_LIST.OPERATOR,
    ],
    order: {
      [ROLE_LIST.APPLICANT]: 7,
      [ROLE_LIST.MINISTRY_DXSH_B_B]: 7,
      [ROLE_LIST.MINISTRY_M_B_B]: 7,
      [ROLE_LIST.DEPUTY_MINISTRY]: 7,
      [ROLE_LIST.MINISTRY]: 7,
      [ROLE_LIST.MINISTRY_FINANCE]: 7,
      [ROLE_LIST.REGION_OPERATOR]: 7,
      [ROLE_LIST.BASIN_B_B]: 7,
      [ROLE_LIST.OPERATOR]: 7,
    },
  },
  // Moliyalashtirish grafigi
  {
    id: "/finans",
    label: "Financial Plans",
    icon: Finans,
    href: "/finans",
    allowedRoles: [ROLE_LIST.APPLICANT, ROLE_LIST.BASIN_B_B, ROLE_LIST.BALANCE],
    order: {
      [ROLE_LIST.APPLICANT]: 8,
      [ROLE_LIST.BASIN_B_B]: 8,
      [ROLE_LIST.BALANCE]: 8,
    },
  },
  // Investitsion majburiyatlar
  {
    id: "/investments",
    label: "Investment obligation",
    icon: Investment,
    href: "/investments",
    allowedRoles: [ROLE_LIST.APPLICANT, ROLE_LIST.BASIN_B_B, ROLE_LIST.BALANCE],
    order: {
      [ROLE_LIST.APPLICANT]: 9,
      [ROLE_LIST.BASIN_B_B]: 9,
      [ROLE_LIST.BALANCE]: 9,
    },
  },
  // Dalolatnoma Tuzish
  {
    id: "/deed",
    label: "Deed",
    icon: Deed,
    href: "/deed",
    allowedRoles: [ROLE_LIST.APPLICANT, ROLE_LIST.BALANCE],
    order: {
      [ROLE_LIST.APPLICANT]: 10,
      [ROLE_LIST.BALANCE]: 10,
    },
  },
  // Talabnoma tuzish shakillantirish
  {
    id: "/applicationform",
    label: "Application form",
    icon: ApplicationsForm,
    href: "/applicationform",
    allowedRoles: [ROLE_LIST.APPLICANT, ROLE_LIST.BASIN_B_B, ROLE_LIST.BALANCE],
    order: {
      [ROLE_LIST.APPLICANT]: 11,
      [ROLE_LIST.BASIN_B_B]: 11,
      [ROLE_LIST.BALANCE]: 11,
    },
  },
  //Konsepsiya qo'shish
  // {
  //   id: "/add",
  //   label: "Concept",
  //   icon: Monitoring,
  //   href: "/add",
  //   allowedRoles: [ROLE_LIST.APPLICANT],
  //   order: {
  //     [ROLE_LIST.APPLICANT]: 12,
  //   },
  // },
  // Hisobot
  {
    id: "/electricity",
    label: "Reports",
    icon: Reports,
    href: "/electricity",
    allowedRoles: [
      ROLE_LIST.BALANCE,
      ROLE_LIST.MINISTRY_DXSH_B_X,
      ROLE_LIST.REGION_OPERATOR,
      ROLE_LIST.MINISTRY_DXSH_B_B,
      ROLE_LIST.MINISTRY_M_B_B,
      ROLE_LIST.OPERATOR,
      ROLE_LIST.DEPUTY_MINISTRY,
      ROLE_LIST.MINISTRY,
      ROLE_LIST.MINISTRY_FINANCE,
      ROLE_LIST.FINANCE_EMPLOYEE,
      ROLE_LIST.HEAD,
    ],
    order: {
      [ROLE_LIST.HEAD]: 13,
      [ROLE_LIST.OPERATOR]: 13,
      [ROLE_LIST.REGION_OPERATOR]: 13,
      [ROLE_LIST.APPLICANT]: 13,
    },
  },
];
